server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#引入dubbo的配置
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user     #定义服务名称
  registry:                 #定义注册中心链接
    address: zookeeper://192.168.87.128:2181?backup=192.168.87.128:2182,192.168.87.128:2183